helloworld: helloworld.cpp
	g++ helloworld.cpp -o helloworld

basic_variables: basic_variables.cpp
	g++ basic_variables.cpp -o basic_variables

basic_types: basic_types.cpp
	g++ basic_types.cpp -o basic_types

basic_intsum: basic_intsum.cpp
	g++ basic_intsum.cpp -o basic_intsum

random_bits: random_bits.cpp
	g++ random_bits.cpp -o random_bits

swap_wrong: swap_wrong.cpp
	g++ swap_wrong.cpp -o swap_wrong

swap_wrong_debug: swap_wrong_debug.cpp
	g++ swap_wrong_debug.cpp -o swap_wrong_debug

swap_ptr: swap_ptr.cpp
	g++ swap_ptr.cpp -o swap_ptr

swap_ref: swap_ref.cpp
	g++ swap_ref.cpp -o swap_ref

static_id: static_id.cpp
	g++ static_id.cpp -o static_id

clean:
	rm -f helloworld
	rm -f basic_variables
	rm -f basic_types
	rm -f basic_intsum
	rm -f random_bits
	rm -f swap_wrong
	rm -f swap_wrong_debug
	rm -f swap_ptr
	rm -f swap_ref
	rm -f static_id
