helloworld: helloworld.cpp
	g++ helloworld.cpp -o helloworld

basic_variables: basic_variables.cpp
	g++ basic_variables.cpp -o basic_variables

basic_types: basic_types.cpp
	g++ basic_types.cpp -o basic_types

basic_intsum: basic_intsum.cpp
	g++ basic_intsum.cpp -o basic_intsum

random_bits: random_bits.cpp
	g++ random_bits.cpp -o random_bits

clean:
	rm -f helloworld
	rm -f basic_variables
	rm -f basic_types
	rm -f basic_intsum
	rm -f random_bits
